### ISSUE TITLE
element throws an exception when validate() is called without setting the value

### ISSUE THREAD

**Issue by cherukumilli** [biztek/hipaa-dea-number-input#1]
When the value of the hippa-dea-number-input is not set then the `validate()` call throws an exception instead of an error on line 62.

Error message in the chrome developer tools:

```
hipaa-dea-number-input.html:62 Uncaught TypeError: Cannot read property 'substr' of undefined(…)
```

Handle this gracefully with an error instead of killing the element.

**Action required:**
- [x] Write a test case to recreate this error
- [x] Fix this error and ensure the test case succeeds
- [x] Update ReadMe to describe this element. Include doc that says what is the right format and what is the wrong format. Include few samples of good DEA Number’s.

**Comment by sricharan123** [comment]
fixed.

**Comment by cherukumilli** [comment]
@rajkumarajce 
Please review this code
