### ISSUE TITLE
Demo Page: The validate method is not clearing the error message after entering the valid value

### ISSUE THREAD

**Issue by anushagadepalli** [biztek/hipaa-dea-number-input#7]
Steps to recreate:
1. Open the demo page of the element `http://127.0.0.1:<PORT>/components/hipaa-dea-number-input/demo/`
2. Enter an invalid DEA Number: `B26125341`
3. Click on `Validate` button
4. `DEA Number is invalid` error message appears
5. Change the DEA Number to a valid number: `BJ6125341`
6. Click on `Validate` button
7. `DEA Number is invalid` error message still appears

Expected behavior:
The error message should disappear after `step 6`

**Comment by cherukumilli** [comment]
@anushagadepalli 
Looks like you fixed this problem in one of your PR's.
Please update this issue with the PR number and close this issue.

**Comment by anushagadepalli** [comment]
@cherukumilli 
Yes I fixed this issue in PR #8.
I am closing this issue.
